HumanSignal/label-studio-sdk

- label_studio_sdk/users.py
Fixes issue #22 
Correct pydantic validation error when doing `Client.get_users()` using community edition.
> [fix] Optional org_membership for community edition

- Makefile
- label_studio_sdk/client.py
- requirements.txt
- tests/test_client.py
This pull request aims to make extra headers possible for http requests.
Indeed, deploying LabelStudio may require specific headers as Proxy-Authorization.
Current implementation adds a dict parameter in the client constructor. This may includes extra keys that will be added to the "basic" header `{'Authorization': f'Token {self.api_key}'}`
Run the unit test with make :
```
make test
```
> Allow client extra headers

- label_studio_sdk/client.py
Add a new sync_storage method to the SDK in the client class, may not be needed it could be done with `ls.make_request` but I am submitting it anyway.  
Here is an example of creating a project, attaching S3 storage, and synchronizing storage.  This would result in a project that is ready to start labeling.  All variables have been omitted to protect account information. 
```
from label_studio_sdk import Client
ls = Client(url=label_studio_url, api_key=label_studio_access_token)
project = ls.start_project(title="pull_request", label_config=label_config)
storage = project.connect_s3_import_storage(
bucket=aws_bucket_name,
prefix=aws_bucket_prefix,
use_blob_urls=True,
aws_access_key_id=aws_access_key_id,
aws_secret_access_key=aws_secret_access_key,
) …
```
> added sync_storage method

- label_studio_sdk/project.py
Currently `Path` type is not supported when loading tasks from a file.
This code:
```python
from pathlib import Path
project.import_tasks(Path('./some/path/tasks.json')
```
produces this exception:
```python
+integration-tests-templater *failed* |     def import_tasks(self, tasks, preannotated_from_fields: List = None):
+integration-tests-templater *failed* |         """ Import JSON-formatted labeling tasks. Tasks can be unlabeled or contain predictions.
+integration-tests-templater *failed* |                                                                                                                                    
+integration-tests-templater *failed* |         Parameters …
```
> Allow to provide Path instance as tasks file

- label_studio_sdk/project.py
fixes [45](https://github.com/heartexlabs/label-studio-sdk/issues/45)
This solution simple takes all headers from the used `Client`. The one thing I'm not 100% sure about is that it also uses `Authorization` headers, which means the provided `api_key` is not used anymore in practice (it's overwritten):
```python
if api_key is not None:
warnings.warn("A deprecation warning to fit accordingly to your deprecation policy", DeprecationWarning)
credentials = ClientCredentials(api_key=api_key)
self.api_key = credentials.api_key if credentials.api_key else self.get_api_key(credentials)
self.headers = {'Authorization': f'Token {self.api_key}'}
if extra_headers:
self.headers.update(extra_headers)
```
> Propagate provided 'extra_headers' through `_create_from_id`

- label_studio_sdk/project.py
I added a method to allow for the updating of tasks (specifically for the addition of `meta` k:v pairs, for my use case) via the Python SDK.
I wasn't really sure how to go about adding tests, though the `CONTRIBUTING.md` document encourages us to do so. There aren't any pre-existing tests, so adding tests would probably be a pretty huge effort just for this one addition (since I'd have to think through the best way to test and mock up all these API calls etc). Happy to take guidance on this.
> Add update task method

- requirements.txt
Add compatibility with dependencies that bundle newer `pydantic` versions.
**Issue:** https://github.com/heartexlabs/label-studio-sdk/issues/75
> [fix]: add support for newer pydantic versions

- label_studio_sdk/project.py
The way my IDE (pycharm 2022) parses the docstring of export_snapshot_list, it returns an int.
However, it returns a list of dicts. This fixes it.
> [fix] documentation of the return type of export_snapshot_list in project.py

- label_studio_sdk/project.py
Added method` export_snapshot_delete()` to the `Project` class to address the issue #80
I am not sure about the `export_id` param - I've added it like this to be consistent throughout the SDK, though in [API](https://labelstud.io/api#operation/api_projects_exports_delete) it is named as `export_pk`.
> feat: added delete snapshot method

- docs/pdoc_templates/head.mako
- docs/pdoc_templates/menu.mako
We’re moving the docs to a new theme and these script / css are pointing to the old theme.
To not break the site, I’m pointing the ressources to our old docs theme
> Update links URL

- .gitignore
- label_studio_sdk/client.py
- requirements.txt
- tests/test_client.py
- This PR fixes #139 by addressing issues related to the latest Pydantic 2.0 release (default values for the ClientCredentials model)
- Loosen restrictions on Pydantic version to allow V2
- Fixes client unit tests that were failing on main before
> [fix] bump pydantic version and fix unit tests

- label_studio_sdk/__init__.py
- label_studio_sdk/client.py
- label_studio_sdk/project.py
Before
```
jo@xxc:~/Repos/label-studio-sdk$ PYTHONPATH=. python tests/test_driver.py 
--------------------------------------------
Request URL: https://app.heartex.com/api/tasks?project=34506&page=2&page_size=100&query=%7B%22filters%22%3A+null%2C+%22ordering%22%3A+%5B%5D%2C+%22selectedItems%22%3A+%7B%22all%22%3A+true%2C+%22excluded%22%3A+%5B%5D%7D%7D&fields=all&resolve_uri=True
Response status code: 404
Response content:
{
"id": "...",
"status_code": 404,
"version": "1.8.3dev",
"detail": "Invalid page.",
"exc_info": null
}
SDK error traceback:
proj=34506 got tasks: tasks=[]
```
After
```
jo@xxc:~/Repos/label-studio-sdk$ PYTHONPATH=. python tests/test_driver.py 
proj=39570 got tasks: tasks=[{'id': 65823440, ...}, {'id': 67404521, ...}, {'id': 67404522, ...}] …
```
> fix: LSDV-5564: Suppress error message on normal end of pagination

- label_studio_sdk/project.py
Without this check, using the default (None) would result in TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
> Support null google_application_credentials

- label_studio_sdk/client.py
Corrects #134  
Moving the `cookies` initialization before the `get_api_keys` call to prevent an `AttributeError`.
> fix: Move cookies initialization to prevent client creation errors 

- docs/project.md
SDK project page had a broken image link to a Heidi SVG. There isn't a good substitute for this image, and it isn't necessary for the content, so removing it.
> docs: Remove broken image link

- CONTRIBUTING.md
- README.md
Small update fixing the link in README.md and adding a section about PR naming into CONTRIBUTING.md because for now it's not displayed anywhere except the configuration of GH actions.
> docs: link fix and PR naming section

- label_studio_sdk/client.py
This solves #145 
I just added a check and error message in case the user attempts to instantiate the Client improperly.
Now this is what happens if you instantiate a Client with no arguments and no env var set:
```python
>>> import label_studio_sdk
>>> label_studio_sdk.Client()
```
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/path/to/label_studio_sdk/client.py", line 90, in __init__
raise RuntimeError(
RuntimeError: If neither 'api_key' nor 'credentials' are provided, 'LABEL_STUDIO_API_KEY' environment variable must be set
```
> fix: Adding check for invalid Client instantiation

- label_studio_sdk/users.py
- label_studio_sdk/workspaces.py
`pydantic<3,>1.7` from the `requirements.txt` resolves to v.6.1, which has some backwards incompatibility with v1
Code snippet to reproduce:
```python
from label_studio_sdk import Client
API_KEY = os.environ["LABEL_STUDIO_API_KEY"]
ls = Client(url=LABEL_STUDIO_URL, api_key=API_KEY)
assert ls.check_connection()["status"] == "UP", 'Connection status is not UP'
user_table = ls.get_users()
```
Error:
```shell
pydantic_core._pydantic_core.ValidationError: 1 validation error for User
org_membership
Field required [type=missing, input_value={'id': 1, 'first_name': '...ject at 0x7f9712a4ff50>}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.6/v/missing
```
`Client.get_users` [makes an API call](https://github.com/HumanSignal/label-studio-sdk/blob/7ec493e6e9ff128e08955 …
> fixes for pydantic v2

- setup.py
Fixed installing of the package. I used `pip install -e .` inside the repo folder to test that it did'nt worked before and now works. 
Tested this in python 3.10. 
Error I got before was:
```
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/home/my/cool/path/label-studio-sdk/setup.py", line 16, in <module>
version = re.search(r'__version__ = "(.*?)"', f.read()).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
> fix: version parsing in setup.py 

- setup.py
This MR attempts to exclude the `docs` directory from `setuptools` based on a requested change in the following PR:
https://github.com/conda-forge/staged-recipes/pull/25567
> fix: Excluding docs from setuptools

- label_studio_sdk/label_interface/interface.py
- tests/test_interface/configs.py
- tests/test_interface/test_main.py
Builds on a fix made yesterday - https://github.com/HumanSignal/label-studio-sdk/pull/212
That handled the case where a `value` of a `Label` was an empty string. However in prod it seems we have some projects that dont have a `value` at all - which should be invalid and not pass validation - but somehow they exist. 
Now this change will handle configs like this to not break, we will just be skipping this label for now and not raising an error. Might want to in the future.
```
<View>
<Text name="text" value="$text"/>
<Labels name="type" toName="text">
<Label />
<Label value="" />
</Labels>
</View>
```
> fix: DIA-1123: Handle config with invalid Label tag (no value)

- README.md
README section on using legacy SDK had an error. 
`from label_studio_sdk._legacy import Client`
-->
`from label_studio_sdk import Client`
> docs: Fix import Client command

- src/label_studio_sdk/_extensions/label_studio_tools/core/utils/io.py
Fix download_and_cache for local storage with files in the root dir for label-studio-tools.
> fix: Fix download_and_cache for local storage with files in the root dir

- LICENSE
cheers, 
originally, this project had an apache 2.0 license file (#1) which somehow got lost during the `1.0.0` release. Can we add it back or was this a deliberate action?
> fix: Revert APACHE license back

- src/label_studio_sdk/_extensions/label_studio_tools/core/label_config.py
- src/label_studio_sdk/converter/converter.py
- tests/custom/label_studio_tools/test_core_label_config.py
Parse a labeling config containing an Image tag with `valueList` like so:
```
{'type': 'Image', 'valueList': 'images', 'valueType': None}
```
and in formats calculation, if any input tag has `valueList` in it, set `is_mig` and don't allow COCO, YOLO, YOLO-OBB, or VOC
> fix: LEAP-1379: disable non-functional export types for MIG projects

- poetry.lock
- pyproject.toml
- src/label_studio_sdk/label_interface/control_tags.py
- src/label_studio_sdk/label_interface/interface.py
- src/label_studio_sdk/label_interface/region.py
use [JSF](https://github.com/ghandic/jsf) lib to generate examples for each ControlTag which has `.to_json_schema()` implemented
> feat: DIA-1685: [sdk] Create example predictions and annotations from a LabelConfig

- src/label_studio_sdk/label_interface/control_tags.py
When using `get_labels` for a Rating or Number tag, we were hitting a runtime error trying to get `len(v)` since Rating/Number annotations are not stored in a List like Choices, Labels, etc - it is just an `int`
> fix: DIA-1581: Enhance prompt not working with number/rating tags

- src/label_studio_sdk/converter/imports/yolo.py
This simple PR fixes the default image extension choices when using label-studio-converter to import YOLO data. 
- In `yolo.py`, the function definition for `convert_yolo_to_ls` uses `image_ext=".jpg,.jpeg,.png"` as the default image extension options. However, this default choice is overridden by the default `--image-ext` argument, which is just `".jpg"`.
- The PR changes the default choices in the `--image-ext` argument to match the function default, because it seems like that's what was intended by the original authors of the code.
- It changes the default `--image-ext` argument from `".jpg"` to `".jpg,.jpeg.png"`
Ultimately, this change makes it easier for a new user to use `label-studio-converter` without having to know about the `--image-ext` argument, which isn't documented …
> fix: Change YOLO import default image extension choices to .jpg, .jpeg, .png

- src/label_studio_sdk/converter/converter.py
This change fixes Issue #365, where the export process failed due to polygons with zero points. I added a condition to check for empty polygons and skip those annotations using a `continue` statement. This ensures that only valid polygons with points are processed, preventing the error during export.
> fix: skip invalid labels in exporting procedure

- .github/workflows/tests.yml
- pyproject.toml
Fixes this error when LS SDK is used as a dependency in other builds
```
The Poetry configuration is invalid:
- The fields ['name'] are required in package mode.
```
> fix: LEAP-1758: prevent use of poetry-core 2

- pyproject.toml
- fix pyproject config to make label-studio-converter command available after package installation
> fix: LEAP-1842: Repair label-studio-converter cli

- src/label_studio_sdk/core/client_wrapper.py
- src/label_studio_sdk/tokens/client_ext.py
Previously we were creating a new httpx client for this token refresh call, which works when LabelStudio / AsyncLabelStudio is initialized with default httpx client , but it did not respect user-provided httpx_client. 
The obvious solution is to use that same client, but that turned out to be much more complicated than it sounds. 
In the end I ended up still making a new sync httpx client, but constructed using the same params of the user-provided httpx Client/AsyncClient
> fix: UTC-18: Respect users httpx client for token refresh
